### ISSUE TITLE
Implement apps endpoints in the local API

### ISSUE THREAD

**Issue by syphr42** [syphr42/liblametrictime-java#3]
"apps_action_url": "http://host:8080/api/v2device/apps/{:id}/widgets/{:widget_id}/actions/",
    "apps_get_url": "http://host:8080/api/v2device/apps/{:id}/",
    "apps_list_url": "http://host:8080/api/v2device/apps/",
    "apps_switch_next_url": "http://host:8080/api/v2device/apps/next/",
    "apps_switch_prev_url": "http://host:8080/api/v2device/apps/prev/",
    "apps_switch_url": "http://host:8080/api/v2device/apps/{:id}/widgets/{:widget_id}/activate/",

**Comment by syphr42** [comment]
It looks like the URLs returned by the API (/api/v2) for apps have a typo. There should be slash between 'v2' and 'device'.

**Comment by syphr42** [comment]
I've got most of these working. I haven't quite got the  "app_action_url" figured out yet. All of this by experimentation since these endpoints are not officially documented yet.

The data model is also a bit confusing. When it comes to applications, LaMetric broke from what they were doing and instead of calling each app's section of Json "application" (like they did, for example, with "model" or "sound") or providing a list called "applications" (like they did, for example, with "frames"), they called it with the application's package name. I have dig into Gson to find out how to make this serialize/deserialize correctly.

**Comment by alexrockt** [comment]
Hi, I implemented the API endpoints in Python (https://github.com/alexrockt/lmnotify) and I got the apps working - there is another typo: /action/ instead of /actions/

the json you send with the POST request containts "id":"action.name" (e.g. radio.play) and if you have parameters (e.g. for countdown) the json also needs a "params" key.

Cheers

**Comment by syphr42** [comment]
@alexrockt 

Thanks for the tips! That's a huge help!
